### ISSUE TITLE
cytoolz is required to import blaze, but it's not listed in requirements_strict.txt

### ISSUE THREAD

**Issue by ssanderson** [ContinuumIO/blaze#1036]
In a fresh virtualenv, `pip install blaze && python -c "import blaze"` fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssanderson/.virtualenvs/blaze/local/lib/python2.7/site-packages/blaze/__init__.py", line 18, in <module>
    from .utils import ignoring
  File "/home/ssanderson/.virtualenvs/blaze/local/lib/python2.7/site-packages/blaze/utils.py", line 7, in <module>
    from cytoolz import nth
ImportError: No module named cytoolz
```

Is there a reason cytoolz isn't in the strict requirements if it's necessary to even import the top-level module?

**Comment by cpcloud** [comment]
Looks like a bug. We should probably just catch the import error and use `toolz`.
