### ISSUE TITLE
.isin() Assertion Error

### ISSUE THREAD

**Issue by TDaltonC** [ContinuumIO/blaze#1078]
I'm getting an assertion error with .isin() for blaze when the pandas returns the expected result.
```python
# recentHist is a blaze object 
historiesDF = bz.into(bz.DataFrame, recentHist)
In [22]: recentUserInteractionsDF = historiesDF[historiesDF.userID.isin(['5539cf3471e30cdb503c0dd8'])]
# Returns expected result

In [23]: recentUserInteractions = recentHist[recentHist.userID=='5539cf3471e30cdb503c0dd8']
in [24]: recentUserInteractions
# Returns expected result

in [25]: recentUserInteractions = recentHist[recentHist.userID.isin(['5539cf3471e30cdb503c0dd8'])]
in [26]: recentUserInteractions
Traceback (most recent call last):

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/IPython/core/formatters.py", line 339, in __call__
    return method()

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/interactive.py", line 329, in <lambda>
    Expr._repr_html_ = lambda x: to_html(x)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/interactive.py", line 301, in to_html
    return to_html(concrete_head(expr))

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/interactive.py", line 193, in concrete_head
    return odo(head, DataFrame)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/odo/odo.py", line 90, in odo
    return into(target, source, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/interactive.py", line 316, in into
    result = compute(b, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/interactive.py", line 178, in compute
    return compute(expr, resources, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/compute/core.py", line 470, in compute
    result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/compute/core.py", line 164, in top_then_bottom_then_top_again_etc
    expr2, scope2 = bottom_up_until_type_break(expr, scope, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/compute/core.py", line 348, in bottom_up_until_type_break
    for i in inputs])

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/compute/core.py", line 371, in bottom_up_until_type_break
    **kwargs)}

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)

  File "/Users/Dalton/anaconda/envs/dopamine/lib/python2.7/site-packages/blaze/compute/mongo.py", line 215, in compute_up
    assert isinstance(predicate, Broadcast)

AssertionError 

```

**Comment by cpcloud** [comment]
Hey @TDaltonC thanks for digging in on these issues! I don't think isin was implemented for mongo. Still, that shouldn't trigger an AssertionError. I'll take a look.

**Comment by TDaltonC** [comment]
No problem @cpcloud! Just glad to hear I'm not a nuisance. Here's the ex-issue that made me think about trying it: https://github.com/ContinuumIO/blaze/issues/637

I think that this is a really great project. And I'm glad to play with it.
