### ISSUE TITLE
import blaze error -- Blueprint not defined

### ISSUE THREAD

**Issue by zyzhu2000** [ContinuumIO/blaze#1086]
If I do import blaze, I get the following. This is version 0.8 on python 2.7 on Ubuntu 64-bit.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/alldata/home/gzhu/virtualenv_support/research/lib/python2.7/site-packages/blaze/__init__.py", line 39, in <module>
    from .server import *
  File "/alldata/home/gzhu/virtualenv_support/research/lib/python2.7/site-packages/blaze/server/__init__.py", line 3, in <module>
    from .server import Server, to_tree, from_tree, api
  File "/alldata/home/gzhu/virtualenv_support/research/lib/python2.7/site-packages/blaze/server/server.py", line 33, in <module>
    api = Blueprint('api', __name__)
NameError: name 'Blueprint' is not defined
```

**Comment by cpcloud** [comment]
Thanks for the report. Fix coming up.

**Comment by cpcloud** [comment]
After #1087 you'll get a proper `ImportError` telling you that flask can't be imported.
