### ISSUE TITLE
transform fail case

### ISSUE THREAD

**Issue by groutr** [ContinuumIO/blaze#1124]
blaze.transform does not like the following situation.
Scenario: Try to calculate the relative sizes of each team to the total number of people and append this to the table.
```python
# the dataset
testdata = blaze.Data([(1, 'Alice', 100),
                       (2, 'Bob', -200),
                       (1, 'Charlie', 300),
                       (2, 'Denis', 400),
                       (1, 'Edith', -500)], fields=['team', 'name', 'balance'])
t1 = blaze.by(testdata.team, size=testdata.team.count())
```
```python
# This succeeds
t2 = blaze.transform(t1, new_col=testdata.size/5)
blaze.compute(t2, testdata)
```
```python
# This fails
nr = testdata.nrows    # == 5
t2 = blaze.transform(t1, new_col=testdata.size/nr)
blaze.compute(t2, testdata)
Traceback (most recent call last):
  File "<ipython-input-32-b27996d8fb1e>", line 1, in <module>
    list(blaze.compute(t2, testdata))
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/blaze/compute/core.py", line 70, in compute
    return compute(expr, {first(ts): o}, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/blaze/compute/core.py", line 470, in compute
    result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/blaze/compute/core.py", line 177, in top_then_bottom_then_top_again_etc
    expr3 = optimize_(expr2, *[scope3[leaf] for leaf in expr2._leaves()])
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/blaze/compute/core.py", line 177, in <listcomp>
    expr3 = optimize_(expr2, *[scope3[leaf] for leaf in expr2._leaves()])
KeyError: _2
```

We can also see the following when trying to add a constant column.
```python
# This fails
nr = testdata.nrows    # == 5
t2 = blaze.transform(t1, new_col=nr)
blaze.compute(t2, testdata)
Traceback (most recent call last):
  File "<ipython-input-46-89970307d08b>", line 1, in <module>
    blaze.compute(t2, testdata)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/blaze/compute/core.py", line 70, in compute
    return compute(expr, {first(ts): o}, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/blaze/compute/core.py", line 470, in compute
    result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)
  File "/Users/xxxxx/miniconda/envs/py3k/lib/python3.4/site-packages/blaze/compute/core.py", line 191, in top_then_bottom_then_top_again_etc
    "data: %s" % (expr3, scope4))
NotImplementedError: Don't know how to compute:
expr: Merge(_child=_2, children=(by(_2.team, size=count(_2.team)), label(nelements(_2), 'new_col')))
data: {_2: [(1, 'Alice', 100), (2, 'Bob', -200), (1, 'Charlie', 300), (2, 'Denis', 400), (1, 'Edith', -500)]}
```
I'm guessing that blaze does not know how to evaluate ```nr```.  This is something I would expect blaze to be able to do.

**Comment by chdoig** [comment]
This works:

```python
In [1]: testdata = blaze.Data([(1, 'Alice', 100),
                       (2, 'Bob', -200),
                       (1, 'Charlie', 300),
                       (2, 'Denis', 400),
                       (1, 'Edith', -500)], fields=['team', 'name', 'balance'])


In [2]: t1 = blaze.by(testdata.team, size=testdata.team.count())

In [3]: nr = int(testdata.nrows) # or nr = blaze.compute(testdata.nrows)

In [4]: t2 = blaze.transform(t1, new_col=t1.size/nr)

In [5]: t2
Out[5]: 
   team  size  new_col
0     1     3      0.6
1     2     2      0.4

```


The problem is that `nr` is not an `int`, is a custom blaze number of elements representation, which blaze knows how to print. If you want to evaluate it and transform it to a type that you can operate on, then you have call `int` or  `compute` on it `nr = int(testdata.nrows)` or `nr = compute(testdata.nrows)`.

```python
In [1]: nr = testdata.nrows

In [2]: nr
Out[2]: 5

In [3]: type(_)
Out[3]: blaze.expr.reductions.nelements


In [36]: blaze.compute(nr)
Out[36]: 5

In [37]: type(_)
Out[37]: int
```

**Comment by groutr** [comment]
Fascinating.  I just assumed that ```nr``` was an int because it looked like an int and acted like an int.  Maybe clarification of return types in the documentation would help (like numpy)?

Does .shape not take into account missing data?

**Comment by cpcloud** [comment]
`shape` could be multiple dimensions, `nrows` is roughly `shape[0]`. sometimes we may have `var` as one of our dimensions (this comes up with tables whose row count can't be computed from the expression alone) and `nrows` will actually trigger the computation where as `shape[0]` will be `var`.

@groutr can you make a documentation issue about clarifying this? thanks for reporting!

**Comment by groutr** [comment]
Another idea would be to return the ```__repr__``` of the blaze expression something like
```
<blaze.expr.reductions.nelements: 5>
```

**Comment by cpcloud** [comment]
The main issue here is blaze needs to know to pass over the data twice: once to compute `nr` and another to compute the final result involving the computed `nr`. This has come up a few times. I'll look into fixing it for the next release (0.8.2)
