### ISSUE TITLE
Blaze server yaml file error

### ISSUE THREAD

**Issue by chdoig** [ContinuumIO/blaze#1181]
Testing the Blaze server from a file and getting the following error:

```python
$ blaze-server server.yaml
Traceback (most recent call last):
  File "/anaconda/envs/ep-blaze/bin/blaze-server", line 6, in <module>
    sys.exit(_main())
  File "/anaconda/envs/ep-blaze/lib/python2.7/site-packages/blaze/server/spider.py", line 130, in _main
    ignore = tuple(getattr(__builtins__, e) for e in args.ignored_exception)
  File "/anaconda/envs/ep-blaze/lib/python2.7/site-packages/blaze/server/spider.py", line 130, in <genexpr>
    ignore = tuple(getattr(__builtins__, e) for e in args.ignored_exception)
AttributeError: 'dict' object has no attribute 'Exception'
```

I believe problem is in this line:
https://github.com/ContinuumIO/blaze/blob/06991f6d368f23700019e36b337ea2800f37ab14/blaze/server/spider.py#L130
when no ignored_exception in the args is passed.

**Comment by cpcloud** [comment]
Sorry for the delay. Thanks for finding this.
